import { getInstantDB } from "./config"
import { MedusaError } from "@medusajs/framework/utils"

/**
 * Verify InstantDB token and return user info
 * Note: InstantDB handles auth differently - tokens are managed client-side
 * For server-side verification, we'll use the admin SDK to query user data
 */
export async function verifyInstantDBToken(
  token: string
): Promise<{
  uid: string
  email?: string
  email_verified?: boolean
  role?: string
  vendor_id?: string
  [key: string]: any
}> {
  try {
    const db = getInstantDB()
    
    // InstantDB tokens are typically JWT tokens that can be verified
    // For now, we'll extract user info from the token payload
    // In production, you should verify the token signature
    
    // Parse JWT token (basic parsing - in production use a proper JWT library)
    const parts = token.split(".")
    if (parts.length !== 3) {
      throw new Error("Invalid token format")
    }

    const payload = JSON.parse(
      Buffer.from(parts[1], "base64url").toString("utf-8")
    )

    return {
      uid: payload.sub || payload.user_id || payload.id,
      email: payload.email,
      email_verified: payload.email_verified,
      role: payload.role,
      vendor_id: payload.vendor_id,
      ...payload,
    }
  } catch (error: any) {
    throw new MedusaError(
      MedusaError.Types.UNAUTHORIZED,
      `InstantDB token verification failed: ${error.message}`
    )
  }
}

/**
 * Get user by ID using InstantDB
 */
export async function getInstantDBUser(uid: string) {
  try {
    const db = getInstantDB()
    
    // Query user from InstantDB
    // Note: This assumes you have a users entity in your schema
    // You may need to adjust based on your actual schema
    const { data } = await db.query({
      users: {
        $: {
          where: { id: uid },
        },
      },
    })

    return data?.users?.[0] || null
  } catch (error: any) {
    throw new Error(`Failed to get InstantDB user: ${error.message}`)
  }
}

/**
 * Create authentication token for user
 * Note: InstantDB handles token creation client-side
 * This is mainly for reference
 */
export async function createAuthToken(
  userId: string,
  additionalClaims?: Record<string, any>
) {
  // InstantDB tokens are created client-side via db.auth methods
  // This function is kept for API compatibility
  // In practice, tokens are generated by InstantDB's auth system
  return {
    token: "instantdb_token", // Placeholder - actual tokens come from client
    userId,
    claims: additionalClaims,
  }
}

